services:
  # MySQL 데이터베이스
  db:
    image: mysql:8.0
    container_name: jeonjueats-db-prod
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-jeonjueats_prod_password_2025}
      MYSQL_DATABASE: ${DB_NAME:-jeonjueats}
      MYSQL_USER: ${DB_USERNAME:-jeonjueats_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-jeonjueats_prod_password_2025}
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --skip-host-cache --skip-name-resolve
    networks:
      - jeonjueats-network
    restart: unless-stopped

  # Spring Boot 백엔드 (프로덕션)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: jeonjueats-backend-prod
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-jeonjueats}
      DB_USERNAME: ${DB_USERNAME:-jeonjueats_user}
      DB_PASSWORD: ${DB_PASSWORD:-jeonjueats_prod_password_2025}
      JWT_SECRET: ${JWT_SECRET:-jeonjueats-secure-jwt-secret-key-for-production-change-this-in-real-deployment}
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - jeonjueats-network
    restart: unless-stopped

  # 일반 사용자용 Vue.js 프론트엔드 (프로덕션)
  frontend-user:
    build:
      context: ./frontend/jeonjueats-user-app
      dockerfile: Dockerfile
    container_name: jeonjueats-frontend-user-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - jeonjueats-network
    restart: unless-stopped

  # 사장님용 Vue.js 프론트엔드 (프로덕션)
  frontend-owner:
    build:
      context: ./frontend/jeonjueats-owner-app
      dockerfile: Dockerfile
    container_name: jeonjueats-frontend-owner-prod
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - jeonjueats-network
    restart: unless-stopped

# 볼륨 설정
volumes:
  mysql_data_prod:
    driver: local

# 네트워크 설정
networks:
  jeonjueats-network:
    driver: bridge