server:
  port: 8080

spring:
  application:
    name: jeonjueats-backend
  
  # 기본 프로필을 dev로 설정 (개발용)
  profiles:
    active: dev
  
  # H2 데이터베이스 설정 (개발용)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 콘솔 설정 (웹에서 데이터베이스 확인 가능)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발 초기에는 create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 5MB      # 파일 하나당 최대 5MB
      max-request-size: 10MB  # 전체 요청 최대 10MB
  
  # 시큐리티 기본 설정 (나중에 JWT로 대체)
  security:
    user:
      name: admin
      password: admin123

# JWT 설정
jwt:
  secret: jeonjueats-secret-key-for-development-only-change-in-production
  expiration: 86400000  # 24시간 (밀리초)

# 파일 업로드 저장 경로
file:
  upload-dir: ./uploads/

# 로깅 설정
logging:
  level:
    com.jeonjueats: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

---
# 운영 환경 설정 (나중에 사용)
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:mysql://localhost:3306/jeonjueats?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: your_password_here
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  h2:
    console:
      enabled: false  # 운영에서는 H2 콘솔 비활성화
  
  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 validate 사용
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.jeonjueats: INFO
    org.springframework.security: WARN